/*
 * Standalone unit test for ngx_ff_jwt (Phase F, F.3 + F.4). Reads
 * "code<TAB>configAlg<TAB>leeway<TAB>token" lines (see jwt_gen.mjs) from stdin and
 * asserts each token verifies to the expected result under the pinned algorithm, using
 * the HMAC secret / PEM public keys generated by the Node harness. Also runs a
 * dedicated kid-selection sub-test against a two-key set.
 *
 * Build:  cc -Wall -Wextra test_ff_jwt.c ../ngx_ff_jwt.c -lcrypto -o /tmp/test_ff_jwt
 * Run:    node jwt_gen.mjs <secret> <now> <keydir> \
 *             | /tmp/test_ff_jwt <secret> <now> <keydir>
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include <openssl/evp.h>
#include <openssl/pem.h>

#include "../ngx_ff_jwt.h"

static EVP_PKEY *
load_pem(const char *dir, const char *name)
{
    char       path[4096];
    BIO       *bio;
    EVP_PKEY  *pkey;

    snprintf(path, sizeof(path), "%s/%s", dir, name);
    bio = BIO_new_file(path, "r");
    if (!bio) {
        fprintf(stderr, "cannot open %s\n", path);
        exit(2);
    }
    pkey = PEM_read_bio_PUBKEY(bio, NULL, NULL, NULL);
    BIO_free(bio);
    if (!pkey) {
        fprintf(stderr, "cannot parse %s\n", path);
        exit(2);
    }
    return pkey;
}

static char *
read_file(const char *dir, const char *name)
{
    char    path[4096];
    FILE   *f;
    char   *buf;
    size_t  n;

    snprintf(path, sizeof(path), "%s/%s", dir, name);
    f = fopen(path, "r");
    if (!f) {
        fprintf(stderr, "cannot open %s\n", path);
        exit(2);
    }
    buf = malloc(65536);
    n = fread(buf, 1, 65535, f);
    fclose(f);
    while (n > 0 && (buf[n - 1] == '\n' || buf[n - 1] == '\r')) {
        n--;
    }
    buf[n] = '\0';
    return buf;
}

int
main(int argc, char **argv)
{
    const char  *secret, *keydir;
    long long    now;
    char         line[16384];
    int          total = 0, failed = 0;
    EVP_PKEY    *es1, *es2, *rs, *ed;
    ff_jwt_key_t two[2];

    if (argc != 4) {
        fprintf(stderr, "usage: %s <secret> <now> <keydir>\n", argv[0]);
        return 2;
    }

    secret = argv[1];
    now = atoll(argv[2]);
    keydir = argv[3];

    es1 = load_pem(keydir, "es1.pem");
    es2 = load_pem(keydir, "es2.pem");
    rs  = load_pem(keydir, "rs.pem");
    ed  = load_pem(keydir, "ed.pem");

    while (fgets(line, sizeof(line), stdin) != NULL) {
        char             *t1, *t2, *t3, *nl;
        int               expected;
        const char       *alg, *token;
        long              leeway;
        ff_jwt_key_t      k;
        ff_jwt_params_t   p;
        ff_jwt_result_t   got;

        nl = strchr(line, '\n');
        if (nl) *nl = '\0';
        if (line[0] == '\0') continue;

        t1 = strchr(line, '\t');       if (!t1) continue; *t1 = '\0';
        t2 = strchr(t1 + 1, '\t');     if (!t2) continue; *t2 = '\0';
        t3 = strchr(t2 + 1, '\t');     if (!t3) continue; *t3 = '\0';

        expected = atoi(line);
        alg = t1 + 1;
        leeway = atol(t2 + 1);
        token = t3 + 1;

        memset(&p, 0, sizeof(p));
        memset(&k, 0, sizeof(k));
        p.now = now;
        p.leeway = leeway;

        if (strcmp(alg, "HS256") == 0) {
            p.expected_alg = FF_JWT_ALG_HS256;
            p.key = (const unsigned char *) secret;
            p.key_len = strlen(secret);
        } else {
            if (strcmp(alg, "RS256") == 0) { p.expected_alg = FF_JWT_ALG_RS256; k.pkey = rs; }
            else if (strcmp(alg, "ES256") == 0) { p.expected_alg = FF_JWT_ALG_ES256; k.pkey = es1; }
            else if (strcmp(alg, "EdDSA") == 0) { p.expected_alg = FF_JWT_ALG_EDDSA; k.pkey = ed; }
            else { fprintf(stderr, "unknown alg %s\n", alg); failed++; total++; continue; }
            p.keys = &k;
            p.keys_count = 1;
        }

        got = ff_jwt_verify((const unsigned char *) token, strlen(token), &p);

        total++;
        if ((int) got != expected) {
            failed++;
            fprintf(stderr, "FAIL[%s]: expected %d (%s), got %d (%s)\n  %.60s...\n",
                    alg, expected, ff_jwt_strerror((ff_jwt_result_t) expected),
                    (int) got, ff_jwt_strerror(got), token);
        }
    }

    /* --- kid-selection sub-test: two ES256 keys tagged k1 / k2 --- */
    {
        struct { const char *file; int expected; } cases[] = {
            {"kid_ok.jwt",      FF_JWT_OK},             /* kid k2 → selects es2 */
            {"kid_unknown.jwt", FF_JWT_BAD_SIGNATURE},  /* kid kX → no key */
            {"kid_none.jwt",    FF_JWT_BAD_SIGNATURE},  /* no kid, 2 keys → ambiguous */
        };
        size_t i;

        memset(two, 0, sizeof(two));
        two[0].kid = "k1"; two[0].kid_len = 2; two[0].pkey = es1;
        two[1].kid = "k2"; two[1].kid_len = 2; two[1].pkey = es2;

        for (i = 0; i < sizeof(cases) / sizeof(cases[0]); i++) {
            ff_jwt_params_t  p;
            ff_jwt_result_t  got;
            char            *tok = read_file(keydir, cases[i].file);

            memset(&p, 0, sizeof(p));
            p.expected_alg = FF_JWT_ALG_ES256;
            p.keys = two;
            p.keys_count = 2;
            p.now = now;

            got = ff_jwt_verify((const unsigned char *) tok, strlen(tok), &p);
            total++;
            if ((int) got != cases[i].expected) {
                failed++;
                fprintf(stderr, "FAIL[kid %s]: expected %d, got %d (%s)\n",
                        cases[i].file, cases[i].expected, (int) got, ff_jwt_strerror(got));
            }
            free(tok);
        }
    }

    /* --- claim sub-test (iss / aud / require), HS256 --- */
    {
        struct {
            const char *file, *iss, *aud, *cname, *cval;
            int         expected;
        } cases[] = {
            {"c_iss_ok.jwt",   "https://ff", NULL, NULL, NULL,  FF_JWT_OK},
            {"c_iss_bad.jwt",  "https://ff", NULL, NULL, NULL,  FF_JWT_CLAIM_MISMATCH},
            {"c_iss_miss.jwt", "https://ff", NULL, NULL, NULL,  FF_JWT_CLAIM_MISMATCH},
            {"c_aud_str.jwt",  NULL, "myapi", NULL, NULL,       FF_JWT_OK},
            {"c_aud_arr.jwt",  NULL, "myapi", NULL, NULL,       FF_JWT_OK},
            {"c_aud_bad.jwt",  NULL, "myapi", NULL, NULL,       FF_JWT_CLAIM_MISMATCH},
            {"c_scope_ok.jwt", NULL, NULL, "scope", "admin",    FF_JWT_OK},
            {"c_scope_bad.jwt",NULL, NULL, "scope", "admin",    FF_JWT_CLAIM_MISMATCH},
            {"c_roles_ok.jwt", NULL, NULL, "roles", "admin",    FF_JWT_OK},
        };
        size_t  i;

        for (i = 0; i < sizeof(cases) / sizeof(cases[0]); i++) {
            ff_jwt_params_t  p;
            ff_jwt_result_t  got;
            char            *tok = read_file(keydir, cases[i].file);

            memset(&p, 0, sizeof(p));
            p.expected_alg = FF_JWT_ALG_HS256;
            p.key = (const unsigned char *) secret;
            p.key_len = strlen(secret);
            p.now = now;
            if (cases[i].iss) { p.iss = cases[i].iss; p.iss_len = strlen(cases[i].iss); }
            if (cases[i].aud) { p.aud = cases[i].aud; p.aud_len = strlen(cases[i].aud); }
            if (cases[i].cname) {
                p.claim_name = cases[i].cname; p.claim_name_len = strlen(cases[i].cname);
                p.claim_value = cases[i].cval; p.claim_value_len = strlen(cases[i].cval);
            }

            got = ff_jwt_verify((const unsigned char *) tok, strlen(tok), &p);
            total++;
            if ((int) got != cases[i].expected) {
                failed++;
                fprintf(stderr, "FAIL[claim %s]: expected %d, got %d (%s)\n",
                        cases[i].file, cases[i].expected, (int) got, ff_jwt_strerror(got));
            }
            free(tok);
        }
    }

    EVP_PKEY_free(es1);
    EVP_PKEY_free(es2);
    EVP_PKEY_free(rs);
    EVP_PKEY_free(ed);

    printf("%d/%d passed\n", total - failed, total);
    return failed == 0 ? 0 : 1;
}
