# shellcheck shell=bash
# Router-sim topology library (Pi-router epic — netns simulation harness).
#
# Builds a rootless three-namespace router topology that mirrors the netdevice
# datapath, WITHOUT the physical Raspberry Pi and WITHOUT sudo (runs inside a
# `unshare --user --map-root-user --mount --net` userns where we are mapped root):
#
#   client-ns            router-ns (the datapath)              wan-ns (the "ISP")
#   ┌────────┐   lan0   ┌───────────────────────────┐  wan0  ┌──────────────────┐
#   │ udhcpc │◄────────►│ lan0: dnsmasq DHCP server  │◄──────►│ dnsmasq DHCP srv │
#   │ client │ 10.20/24 │ wan0: udhcpc DHCP client   │10.10/24│ + TCP echo svc   │
#   └────────┘          │ nft:  NAT44 + forward      │        └──────────────────┘
#                       └───────────────────────────┘
#
# The nft ruleset + dnsmasq.conf are generated by the REAL core builders
# (see gen-config.mjs); the WAN/LAN DHCP and NAT paths use real udhcpc/dnsmasq/nft.

set -euo pipefail

# --- addressing (both segments are /24 for sim simplicity) --------------------
WAN_SRV_ADDR="10.10.0.1"      # wan-ns (ISP) address + gateway + service host
WAN_DHCP_RANGE="10.10.0.10,10.10.0.20"
LAN_ADDR="10.20.0.1"          # router lan0 address = LAN gateway
LAN_PREFIX="24"
WAN_SVC_PORT="9099"

RT=""            # runtime dir (set by sim_prepare_runtime)
PASS=0
FAIL=0

log()  { echo "[sim] $*" >&2; }
step() { echo >&2; echo "── $* ─────────────────────────────" >&2; }

assert() {
    # assert "<description>" <exit-status-of-a-preceding-test>
    local desc="$1" rc="$2"
    if [ "$rc" -eq 0 ]; then
        echo "  ✓ $desc" >&2
        PASS=$((PASS + 1))
    else
        echo "  ✗ $desc" >&2
        FAIL=$((FAIL + 1))
    fi
}

nse() { ip netns exec "$@"; }   # short: run a command in a netns

sim_prepare_runtime() {
    # Shadow /run with a writable tmpfs so `ip netns` (bind-mounts /run/netns)
    # and dnsmasq/udhcpc lease files work under mapped root.
    mount --make-rprivate / 2>/dev/null || true
    mount -t tmpfs tmpfs /run
    mkdir -p /run/netns
    RT="$(mktemp -d /run/router-sim.XXXXXX)"
    log "runtime dir: $RT"

    # Build the setgroups no-op shim (see setgroups-shim.c) so dnsmasq can drop
    # privileges under the rootless userns where setgroups() is denied.
    local cc
    cc="$(command -v cc || command -v gcc || command -v clang)"
    "$cc" -shared -fPIC -O2 -o "$RT/nosetgroups.so" "$(dirname "${BASH_SOURCE[0]}")/setgroups-shim.c"
    SIM_PRELOAD="$RT/nosetgroups.so"
}

# The udhcpc callback (busybox). Applies the lease to the interface so the
# datapath actually works, and appends a BOUND marker we assert on. Both nets
# are /24 in the sim, so we skip dotted-mask→prefix conversion.
sim_write_udhcpc_script() {
    cat > "$RT/udhcpc.script" <<'EOS'
#!/bin/sh
: "${subnet:=255.255.255.0}"
case "$1" in
    deconfig) ip addr flush dev "$interface" 2>/dev/null ;;
    bound|renew)
        ip addr flush dev "$interface"
        ip addr add "$ip/24" dev "$interface"
        [ -n "$router" ] && ip route add default via "$router" 2>/dev/null
        echo "BOUND interface=$interface ip=$ip router=$router lease=$lease" >> "$UDHCPC_LOG"
        ;;
esac
EOS
    chmod +x "$RT/udhcpc.script"
}

sim_build_topology() {
    for ns in wan router client; do ip netns add "$ns"; done

    # uplink: router(wan0) <-> wan-ns(up0)
    ip link add wan0 type veth peer name up0
    ip link set wan0 netns router
    ip link set up0  netns wan

    # downlink: router(lan0) <-> client(cl0)
    ip link add lan0 type veth peer name cl0
    ip link set lan0 netns router
    ip link set cl0  netns client

    # wan-ns (ISP): static address, its own default so it can route replies back
    nse wan ip addr add "$WAN_SRV_ADDR/24" dev up0
    nse wan ip link set up0 up
    nse wan ip link set lo up

    # router: bring links up; wan0 gets its address via udhcpc later, lan0 static
    nse router ip link set wan0 up
    nse router ip link set lan0 up
    nse router ip link set lo up
    nse router ip addr add "$LAN_ADDR/$LAN_PREFIX" dev lan0   # == LanAddress.ensureLanAddress

    # client: link up; address via udhcpc from the router's dnsmasq
    nse client ip link set cl0 up
    nse client ip link set lo up

    log "topology up (wan/router/client, veths wan0<->up0, lan0<->cl0)"
}

# dnsmasq drops privileges to user/group `nobody`/`dip` by default; in our rootless
# userns setgroups() is denied (the kernel forces setgroups=deny once an unprivileged
# gid_map is written), so the drop fails. Pinning user+group to root (= our mapped
# uid/gid 0, a no-op setuid/setgid) skips the failing setgroups. Sim-only — in the real
# NET_ADMIN container dnsmasq runs as root and needs none of this.
SIM_DNSMASQ_SHIM=$'user=root\ngroup=root\nlog-facility=-'

# WAN "ISP": a dnsmasq DHCP server + a one-shot TCP echo service on the WAN host.
sim_start_wan_side() {
    cat > "$RT/wan-dnsmasq.conf" <<EOF
port=0
interface=up0
bind-interfaces
dhcp-authoritative
dhcp-leasefile=/run/wan.leases
dhcp-range=$WAN_DHCP_RANGE,120s
dhcp-option=option:router,$WAN_SRV_ADDR
$SIM_DNSMASQ_SHIM
EOF
    nse wan env LD_PRELOAD="$SIM_PRELOAD" dnsmasq -C "$RT/wan-dnsmasq.conf" -k >"$RT/wan-dnsmasq.log" 2>&1 &
    WAN_DNSMASQ_PID=$!
    log "wan-ns dnsmasq DHCP server started (pid $WAN_DNSMASQ_PID)"
}

# Router WAN client path: busybox udhcpc against the wan-ns DHCP server.
sim_router_wan_udhcpc() {
    UDHCPC_LOG="$RT/wan-udhcpc.log" nse router env UDHCPC_LOG="$RT/wan-udhcpc.log" \
        busybox udhcpc -i wan0 -f -n -q -t 6 -T 1 -s "$RT/udhcpc.script" \
        >"$RT/wan-udhcpc.run.log" 2>&1 || return 1
}

# Apply the REAL generated nft ruleset + sysctls in the router netns.
sim_router_apply_netfilter() {
    nse router nft -f "$RT/router.nft"
    if [ -s "$RT/sysctls" ]; then
        while IFS='=' read -r key val; do
            [ -z "$key" ] && continue
            nse router sysctl -qw "$key=$val" || true
        done < "$RT/sysctls"
    fi
}

# Router LAN server path: dnsmasq with the REAL generated config (buildDnsmasqConfig),
# plus the sim-only root-user shim appended (the real config path is left untouched).
sim_router_start_lan_dnsmasq() {
    cp "$RT/lan0.conf" "$RT/lan0.sim.conf"
    printf '%s\n' "$SIM_DNSMASQ_SHIM" >> "$RT/lan0.sim.conf"
    nse router env LD_PRELOAD="$SIM_PRELOAD" dnsmasq -C "$RT/lan0.sim.conf" -k >"$RT/lan-dnsmasq.log" 2>&1 &
    LAN_DNSMASQ_PID=$!
    log "router dnsmasq LAN DHCP server started (pid $LAN_DNSMASQ_PID)"
}

# Client LAN path: busybox udhcpc against the router's dnsmasq.
sim_client_udhcpc() {
    UDHCPC_LOG="$RT/lan-udhcpc.log" nse client env UDHCPC_LOG="$RT/lan-udhcpc.log" \
        busybox udhcpc -i cl0 -f -n -q -t 8 -T 1 -s "$RT/udhcpc.script" \
        >"$RT/lan-udhcpc.run.log" 2>&1 || return 1
}

sim_cleanup() {
    kill "${WAN_DNSMASQ_PID:-}" "${LAN_DNSMASQ_PID:-}" 2>/dev/null || true
    for ns in wan router client; do ip netns del "$ns" 2>/dev/null || true; done
}
